FROM login-api-base

COPY docker/entrypoint.sh /
COPY docker/supervisor/rest.conf /etc/supervisor/conf.d

COPY scripts /scripts
COPY src /src
RUN cd /src && pip3 install .


WORKDIR /src

EXPOSE 10012

ENTRYPOINT ["/entrypoint.sh"]
